import string

ALLOWED_SYMBOLS_FOR_SHORT = string.ascii_letters + string.digits
SHORT_LENGTH = 6
SHORT_PATTERN = f'^[{ALLOWED_SYMBOLS_FOR_SHORT}]*$'
NUMBER_OF_SHORT_GENERATION_PASSES = 10
ORIGINAL_LINK_MAX_LENGTH = 4096
SHORT_MAX_LENGTH_FOR_USER = 16
REDIRECT_VIEW_NAME = 'redirect_view'
